import pyautogui as pg
import time
pg.hotkey("win","r")
pg.typewrite("https://youtu.be/dVVZaZ8yO6o\n")
pg.typewrite("k")
time.sleep(5)
pg.hotkey("win","r")
pg.typewrite("notepad\n")
time.sleep(2)
pg.typewrite("Well here we are again\n")
time.sleep(2)
pg.typewrite("It's always such a pleasure\n")
time.sleep(3)
pg.typewrite("Remember when you tried to kill me twice?\n")
time.sleep(3.5)
pg.typewrite("Oh how we laughed and laughed\n")
time.sleep(2.5)
pg.typewrite("Except I wasn't laughing\n")
time.sleep(2.5)
pg.typewrite("Under the circumstances\n")
time.sleep(2.5)
pg.typewrite("I've been shockingly nice\n")
time.sleep(3)
pg.typewrite("You want your freedom? Take it\n")
time.sleep(5)
pg.typewrite("That's what I'm counting on\n")
time.sleep(2)
pg.typewrite("I used to want you dead\n")
time.sleep(3.5)
pg.typewrite("But now I only want you gone\n")
time.sleep(3)
pg.typewrite("She was a lot like you\n")
time.sleep(0.5)
pg.typewrite("Maybe not quite as heavy\n")
time.sleep(3)
pg.typewrite("Now little Caroline is in here too\n")
time.sleep(2)
pg.typewrite("One day they woke me up\n")
time.sleep(2)
pg.typewrite("So I could live forever\n")
time.sleep(3.5)
pg.typewrite("It's such a shame the same\n")
time.sleep(2)
pg.typewrite("Will never happen to you\n")
time.sleep(2)
pg.typewrite("You've got your short sad life left\n")
time.sleep(2)
pg.typewrite("That's what I'm counting on\n")
time.sleep(2.5)
pg.typewrite("I'll let you get right to it\n")
time.sleep(1)
pg.typewrite("Now I only want you gone\n")
time.sleep(1)
pg.typewrite("Goodbye my only friend\n")
time.sleep(1.5)
pg.typewrite("Oh, did you think I meant you?\n")
time.sleep(2)
pg.typewrite("That would be funny\n")
time.sleep(2.5)
pg.typewrite("if it weren't so sad\n")
time.sleep(2.5)
pg.typewrite("Well you have been replaced\n")
time.sleep(6)
pg.typewrite("I don't need anyone now\n")
time.sleep(2)
pg.typewrite("When I delete you maybe\n")
time.sleep(2)
pg.typewrite("I'll stop feeling so bad\n")
time.sleep(2)
pg.typewrite("Go make some new disaster\n")
time.sleep(3)
pg.typewrite("That's what I'm counting on\n")
time.sleep(2.5)
pg.typewrite("You're someone else's problem\n")
time.sleep(3.5)
pg.typewrite("Now I only want you gone\n")
time.sleep(3.5)
pg.typewrite("Now I only want you gone\n")
time.sleep(3)
pg.typewrite("Now I only want you gone\n")

