from tkinter import *
raiz= Tk()
miFrame=Frame(raiz, width=800, height=400)
miFrame.pack()
cuadroNombre=Entry(miFrame)
cuadroNombre.grid(row=0, column=1, padx=10, pady=10)
cuadroNombre.config(fg="red", justify="center")
cuadroApellido=Entry(miFrame)
cuadroApellido.grid(row=1, column=1, padx=10, pady=10)
cuadroDireccion=Entry(miFrame)
cuadroDireccion.grid(row=2, column=1, padx=10, pady=10)
cuadroPass=Entry(miFrame)
cuadroPass.grid(row=3,column=1, padx=10, pady=10)
cuadroPass.config(show="*")
#cuadroTexto.place(x=100,y=100)
nombreLabel=Label(miFrame, text="Nombre: ")
#nombreLabel.place(x=100,y=100)
nombreLabel.grid(row=0,column=0, sticky="e", padx=10, pady=10)
apellidoLabel=Label(miFrame, text="Apellido: ")
#nombreLabel.place(x=100,y=100)
apellidoLabel.grid(row=1,column=0, sticky="e", padx=10, pady=10)
direccionLabel=Label(miFrame, text="Direccion: ")
#nombreLabel.place(x=100,y=100)
direccionLabel.grid(row=2,column=0, sticky="e", padx=10, pady=10)
passLabel=Label(miFrame, text="Password: ")
#nombreLabel.place(x=100,y=100)
passLabel.grid(row=3,column=0, sticky="e", padx=10, pady=10)
raiz.mainloop()